@startuml cjm_restaurant
title CJM заведения-партнёра

start
:Передать платформе актуальное меню;
:Получить новый заказ от платформы;
if (Заказ можно выполнить?) then (да)
  :Принять заказ;
  :Передавать статусы приготовления;
  :Сообщить о готовности заказа;
else (нет)
  :Отклонить заказ с причиной;
endif
:Обновить доступность позиций меню;
stop
@enduml
