@startuml cjm_user
title CJM пользователя Авито.Кухни

start
:Открыть каталог заведений;
:Найти заведение по названию;
:Просмотреть доступное меню;
if (Все блюда доступны?) then (да)
  :Указать количество и адрес доставки;
  :Отправить заказ с ключом идемпотентности;
  :Следить за статусом заказа;
else (нет)
  :Обновить меню и заменить недоступное блюдо;
endif
stop
@enduml
